export const COMMON_SEARCH = 'COMMON_SEARCH';
export const COMMON_SET_LOCATION = 'COMMON_SET_LOCATION';
export const COMMON_SET_CATEGORY = 'COMMON_SET_CATEGORY';
export const COMMON_SET_YEAR = 'COMMON_SET_YEAR';
export const COMMON_GET_CITIES = 'COMMON_GET_CITIES';
export const COMMON_SET_YEAR_DISABLED = 'COMMON_SET_YEAR_DISABLED';
